-------ALTERAR NO WEBCONFIG DO PROJETO O NOME DA INSTANCIA DO SERVIDOR


USE [master]
GO

CREATE DATABASE [db_CiaTecnica]

GO
USE [db_CiaTecnica]
GO

CREATE LOGIN db_CiaTecnica   
    WITH PASSWORD = 'db_CiaTecnica'  
GO  

ALTER AUTHORIZATION ON DATABASE::db_CiaTecnica TO db_CiaTecnica;

CREATE TABLE PessoaFisica 
(
Id  INT IDENTITY (1,1) PRIMARY KEY,
Nome NVARCHAR (250) NOT NULL,
Sobrenome NVARCHAR (15) NOT NULL,
CPF  NVARCHAR (250) NOT NULL,
CEP  NVARCHAR (250) NOT NULL,
Logradouro NVARCHAR (250) NOT NULL,
Número NVARCHAR (250) NOT NULL,
DataNasci DATE NOT NULL,
DataCad DATETIME NOT NULL,
Bairro NVARCHAR (250) NOT NULL,
Cidade NVARCHAR (250) NOT NULL,
UF  NVARCHAR (8) NOT NULL,
Complemento   NVARCHAR (50) NULL
);

CREATE TABLE PessoaJuridica 
(
Id  INT IDENTITY (1,1) PRIMARY KEY,
NomeFantasia NVARCHAR (250) NOT NULL,
RazaoSocial NVARCHAR (250) NOT NULL,
CNPJ  NVARCHAR (250) NOT NULL,
CEP  NVARCHAR (250) NOT NULL,
Logradouro NVARCHAR (250) NOT NULL,
Número NVARCHAR (250) NOT NULL,
DataCad DATETIME NOT NULL,
Bairro NVARCHAR (250) NOT NULL,
Cidade NVARCHAR (250) NOT NULL,
UF  NVARCHAR (8) NOT NULL,
Complemento  NVARCHAR (50) NULL
);